# Generated by Django 5.2.18 on 2026-10-09 08:27

import django.db.models.deletion
import matching.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, max_length=30)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.case')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('order', 'Satınalma sifarişi'), ('receipt', 'Qəbul sənədi'), ('invoice', 'Faktura')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to=matching.models.upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('extraction_status', models.CharField(default='pending', max_length=30)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('usage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matching.case')),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('case', 'kind'), name='one_document_per_kind')],
            },
        ),
    ]
